[server]
enableCORS = true
enableXsrfProtection = true
port = 8501  # Only needed for local development

[browser]
serverAddress = "unit-converter-by-hezzi.streamlit.app"  # Remove "https://"

[global]
developmentMode = false
